version: '3.8'

services:
  backend:
    container_name: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres  
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=projections_db
      - DB_PORT=5432
    volumes:
      - ./data:/usr/src/app/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=projections_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: